[package]
name = "mymathboard"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
evalexpr = "11.3.0"
iced = { version = "0.13.1", features = ["canvas"] }
image = "0.25.4"
regex = "1.11.0"
rfd = "0.15.0"
